export const TEST_ACTION = '[App] TEST_ACTION';

//app wide
export const SET_IS_LOGGED_IN_TRUE = '[APP] SET_IS_LOGGED_IN_TRUE';
export const SET_IS_LOGGED_IN_FALSE = '[APP] SET_IS_LOGGED_IN_FALSE';

//auth
export const RESET_LOGIN_FORM = '[login] RESET_LOGIN_FORM';
export const SET_LOGIN_FORM_USERNAME_PROPERTIES = '[login] SET_LOGIN_FORM_USERNAME_PROPERTIES';
export const SET_LOGIN_FORM_PASSWORD_PROPERTIES = '[login] SET_LOGIN_FORM_PASSWORD_PROPERTIES';
export const SET_USER_COOKIE = '[login] SET_USER_COOKIE';
