export const TEST_ACTION = '[App] TEST_ACTION';

//app wide
export const SET_IS_LOGGED_IN_TRUE = '[APP] SET_IS_LOGGED_IN_TRUE';
export const SET_IS_LOGGED_IN_FALSE = '[APP] SET_IS_LOGGED_IN_FALSE';

//auth
export const RESET_AUTH_FORM = '[auth] RESET_AUTH_FORM';
export const SET_AUTH_FORM_EMAIL_PROPERTIES = '[auth] SET_AUTH_FORM_EMAIL_PROPERTIES';
export const SET_AUTH_FORM_PASSWORD_PROPERTIES = '[auth] SET_AUTH_FORM_PASSWORD_PROPERTIES';
export const SET_USER_COOKIE = '[auth] SET_USER_COOKIE';
